# Generated by Django 4.0.5 on 2022-07-15 13:56

from django.db import migrations, models
import ecommerce_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_product_active_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/G.jpg', upload_to=ecommerce_app.models.upload_your_images),
        ),
    ]
